#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Alkomat.Resource", IsApplication=true)]

namespace Alkomat
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int androidcolors = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int blue = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int darkblue = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int darkgreen = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int darkorange = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int darkpurple = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int darkred = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int green = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int orange = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int purple = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int red = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int yellow = 2130968586;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ikona = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int przycisk = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int przyciskMinus = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int przyciskPlus = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07002f
			public const int TextViewKtoraGodzina = 2131165231;
			
			// aapt resource value: 0x7f070033
			public const int TextView_AktualnyWynik = 2131165235;
			
			// aapt resource value: 0x7f070035
			public const int TextView_DopuszczalneStezenie = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int TextView_DopuszczalneStezenieGodzina = 2131165238;
			
			// aapt resource value: 0x7f07000a
			public const int buttonDalej = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int buttonM1 = 2131165197;
			
			// aapt resource value: 0x7f070012
			public const int buttonM2 = 2131165202;
			
			// aapt resource value: 0x7f070017
			public const int buttonM3 = 2131165207;
			
			// aapt resource value: 0x7f07001c
			public const int buttonM4 = 2131165212;
			
			// aapt resource value: 0x7f070021
			public const int buttonM5 = 2131165217;
			
			// aapt resource value: 0x7f070026
			public const int buttonM6 = 2131165222;
			
			// aapt resource value: 0x7f07002b
			public const int buttonM7 = 2131165227;
			
			// aapt resource value: 0x7f07002e
			public const int buttonObliczPromileDalej = 2131165230;
			
			// aapt resource value: 0x7f07000f
			public const int buttonP1 = 2131165199;
			
			// aapt resource value: 0x7f070014
			public const int buttonP2 = 2131165204;
			
			// aapt resource value: 0x7f070019
			public const int buttonP3 = 2131165209;
			
			// aapt resource value: 0x7f07001e
			public const int buttonP4 = 2131165214;
			
			// aapt resource value: 0x7f070023
			public const int buttonP5 = 2131165219;
			
			// aapt resource value: 0x7f070028
			public const int buttonP6 = 2131165224;
			
			// aapt resource value: 0x7f07002d
			public const int buttonP7 = 2131165229;
			
			// aapt resource value: 0x7f070031
			public const int buttonPodajGodzine = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int buttonReklama = 2131165234;
			
			// aapt resource value: 0x7f070037
			public const int buttonWynik = 2131165239;
			
			// aapt resource value: 0x7f07000c
			public const int duzepiwo = 2131165196;
			
			// aapt resource value: 0x7f070005
			public const int editText1 = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int editText2 = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int editText3 = 2131165193;
			
			// aapt resource value: 0x7f070016
			public const int lekkiepiwo = 2131165206;
			
			// aapt resource value: 0x7f070011
			public const int malepiwo = 2131165201;
			
			// aapt resource value: 0x7f070003
			public const int radioButton1 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int radioButton2 = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int radioGroup1 = 2131165186;
			
			// aapt resource value: 0x7f070020
			public const int szampan = 2131165216;
			
			// aapt resource value: 0x7f07000b
			public const int tableRow1 = 2131165195;
			
			// aapt resource value: 0x7f070015
			public const int tableRow2 = 2131165205;
			
			// aapt resource value: 0x7f070010
			public const int tableRow3 = 2131165200;
			
			// aapt resource value: 0x7f07001a
			public const int tableRow4 = 2131165210;
			
			// aapt resource value: 0x7f07001f
			public const int tableRow5 = 2131165215;
			
			// aapt resource value: 0x7f070024
			public const int tableRow6 = 2131165220;
			
			// aapt resource value: 0x7f070029
			public const int tableRow7 = 2131165225;
			
			// aapt resource value: 0x7f070001
			public const int textView1 = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int textView2 = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int textView3 = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int textView4 = 2131165184;
			
			// aapt resource value: 0x7f070034
			public const int textView_AktulnePromile = 2131165236;
			
			// aapt resource value: 0x7f070030
			public const int timePicker1 = 2131165232;
			
			// aapt resource value: 0x7f07000e
			public const int tv1 = 2131165198;
			
			// aapt resource value: 0x7f070013
			public const int tv2 = 2131165203;
			
			// aapt resource value: 0x7f070018
			public const int tv3 = 2131165208;
			
			// aapt resource value: 0x7f07001d
			public const int tv4 = 2131165213;
			
			// aapt resource value: 0x7f070022
			public const int tv5 = 2131165218;
			
			// aapt resource value: 0x7f070027
			public const int tv6 = 2131165223;
			
			// aapt resource value: 0x7f07002c
			public const int tv7 = 2131165228;
			
			// aapt resource value: 0x7f07001b
			public const int wino = 2131165211;
			
			// aapt resource value: 0x7f07002a
			public const int wodkaDuza = 2131165226;
			
			// aapt resource value: 0x7f070025
			public const int wodkaMala = 2131165221;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ObliczPromile = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int podajGodzine = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Reklama = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Wynik = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
